<?php

namespace Modules\Statistics\Providers;

use Illuminate\Support\ServiceProvider;

class ModuleServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(RouteServiceProvider::class);
    }
}
